### ISSUE TITLE
Submitting duplicated tickets in JIRA

### ISSUE THREAD

**Issue by cripher** [fortify-ps/FortifyBugTrackerUtility#52]
We are using v3.6 of FortifyBugTrackerUtility jar to connect to Fortify and update bugs. We have noticed some inconsistent behavior while invoking BugTrackerUtility Jar file.

It looks like when we pass the release name to the jar file, it's using a regex for the release name instead of the exact release name and hence pulling the issues from multiple releases and creating duplicate tickets in JIRA.

Should you have any questions or concerns, please do not hesitate to reach out.

Best regards

**Comment by rsenden** [comment]
This is standard FoD behavior; the FoD API for querying releases only supports wildcard searches. I can't change the current behavior as existing users may be depending on current behavior.

As a work-around you can use the `-FoDReleaseNamePatterns` options instead of `-FoDReleaseName`. Although it may sound counterintuitive, this option should allow you to match exact names. I think you may even be able to use `-FoDReleaseName` and `-FoDReleaseNamePatterns` together, to have FoD return a small list of releases based on the wildcard search, and then have the utility narrow this further down to an exact release name.

Obviously you can also just specify the release id instead of the release name; although slightly less user-friendly, this is more specific and doesn't leave any room for name matching issues.
